const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs'),{pathToFileURL}=require('node:url');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const p=await browser.newPage({viewport:{width:1704,height:1136}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(10000);
 await p.goto(pathToFileURL(path.join(__dirname,'fixture.html')).href);await p.waitForSelector('#listContainer');
 await p.evaluate(()=>{window.saved={list:document.querySelector('#listContainer'),radio:document.querySelector('#leftaction input'),next:document.querySelector('#next'),menu:document.querySelector('#cbtToggleMenu'),parent:document.querySelector('#next').parentNode};window.nativeChanges=0;saved.list.addEventListener('change',()=>nativeChanges++)});
 await p.addStyleTag({path:path.join(__dirname,'../dist/game-ui.css')});await p.addScriptTag({path:path.join(__dirname,'../dist/game-ui.js')});await p.waitForSelector('.dcu-dock-native #next a');
 const summary=async()=>{if(!await p.locator('.dcu-summary').count())await p.locator('.dcu-summary-toggle').click()};
 const arena=async()=>{await p.evaluate(()=>SugarCube.Engine.play('Arena'));await p.waitForSelector('.dcu-dock-native #next a')};
 assert.ok(await p.evaluate(()=>document.querySelector('#listContainer')===saved.list&&document.querySelector('#leftaction input')===saved.radio&&document.querySelector('.dcu-dock-native #next')===saved.next&&document.querySelector('.dcu-dock-native #cbtToggleMenu')===saved.menu));
 assert.equal(await p.locator('#leftaction input').count(),13);assert.equal(await p.locator('.dcu-summary').count(),0);
 // Navigation and summary locate native groups without hiding or selecting actions.
 const beforeJump=await p.evaluate(()=>V.leftaction);
 for(const title of ['右手','左手']){await p.locator('.dcu-nav button').filter({hasText:title}).click();assert.equal(await p.locator('.dcu-summary-rail button[aria-current=location] span').innerText(),title);assert.equal(await p.locator('.dcu-nav button[aria-current=location]').innerText(),title)}
 await p.locator('.dcu-nav button').filter({hasText:'右手'}).click();
 assert.ok(await p.locator('#leftaction').isVisible());assert.ok(await p.locator('#rightaction').isVisible());
 await p.locator('.dcu-summary-rail button').filter({hasText:'左手'}).click();
 assert.equal(await p.evaluate(()=>V.leftaction),beforeJump);assert.equal(await p.evaluate(()=>nativeChanges),0);
 await p.locator('#leftaction label').filter({hasText:'防御'}).click();await summary();await p.waitForFunction(()=>V.leftaction==='guard'&&document.querySelector('.dcu-summary').textContent.includes('防御'));assert.equal(await p.evaluate(()=>nativeChanges),1);
 assert.ok((await p.locator('.dcu-summary-rail').innerText()).includes('防御'));
 await p.locator('.dcu-summary-toggle').click();await p.locator('#cbtToggleMenu .cbtToggle').click();await p.locator('#fixture-scroll').check();assert.ok(await p.locator('#fixture-scroll').isChecked());
 const options=await p.locator('#cbtToggleMenu .cbtOption').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return{top:r.top,bottom:r.bottom}}));assert.ok(options[0].bottom<=options[1].top+1,'menu options must not overlap');await p.locator('#cbtToggleMenu .cbtToggle').click();
 await p.locator('#custom-native').click();assert.equal(await p.evaluate(()=>extraClicks),1);
 await p.getByRole('button',{name:'原版界面 ↗',exact:true}).click();await p.waitForFunction(()=>!document.querySelector('.dcu-shell'));assert.ok(await p.evaluate(()=>saved.next.parentNode===saved.parent&&saved.menu.parentNode===saved.parent&&document.querySelector('#listContainer')===saved.list&&V.leftaction==='guard'));assert.equal(await p.locator('#next').evaluate(e=>getComputedStyle(e).position),'fixed');
 await p.getByRole('button',{name:'启用新版战斗面板',exact:true}).click();await p.waitForSelector('.dcu-shell');await p.locator('#replaceAction a').click();await p.locator('#leftaction label').filter({hasText:'新动作'}).click();await summary();await p.waitForFunction(()=>V.leftaction==='new'&&document.querySelector('.dcu-summary').textContent.includes('新动作'));
 // Exact native shortcut selector still reaches the same SugarCube link.
 await p.evaluate(()=>jQuery('#passages #next a.macro-link').trigger('click'));await p.waitForFunction(()=>V.turn===1);await p.waitForSelector('.dcu-dock-native #next a');
 await p.evaluate(()=>{const n=document.createElement('div');n.id='listContainer';n.innerHTML='<div id="leftaction"><label><input type="radio" checked>替换后原生动作</label></div>';document.querySelector('#listContainer').replaceWith(n);window.replacement=n});await p.waitForFunction(()=>document.querySelector('.dcu-native #listContainer')===replacement);
 await p.evaluate(()=>{V.options.combatControls='lists';SugarCube.Engine.play('Arena')});await p.waitForSelector('.dcu-native select');await p.locator('#leftaction select').selectOption({label:'防御'});await summary();await p.waitForFunction(()=>V.leftaction==='guard'&&document.querySelector('.dcu-summary').textContent.includes('防御'));
 // Disabled attributes stay intact; there is no surrogate submit button.
 await p.evaluate(()=>document.querySelector('#next a').setAttribute('aria-disabled','true'));assert.equal(await p.locator('#next a').getAttribute('aria-disabled'),'true');assert.equal(await p.locator('.dcu-primary').count(),0);
 // Replacing a dock wrapper must still restore at its external anchor.
 await p.evaluate(()=>{window.externalParent=document.querySelector('.passage');const n=document.createElement('span');n.id='next';n.innerHTML='<a href="#">复用链接</a>';window.reusedClicks=0;n.firstChild.onclick=e=>{e.preventDefault();reusedClicks++};document.querySelector('#next').replaceWith(n);window.newNext=n});await p.locator('#next a').click();assert.equal(await p.evaluate(()=>reusedClicks),1);
 await p.getByRole('button',{name:'原版界面 ↗',exact:true}).click();assert.ok(await p.evaluate(()=>newNext.isConnected&&newNext.parentNode===externalParent));await p.getByRole('button',{name:'启用新版战斗面板',exact:true}).click();await p.locator('#next a').click();assert.equal(await p.evaluate(()=>reusedClicks),2);
 await p.evaluate(()=>V.options.combatControls='radio');await arena();
 fs.mkdirSync(path.join(__dirname,'artifacts'),{recursive:true});const layouts=[];
 for(const [name,width,height]of [['tablet',1704,1136],['tablet-portrait',1136,1704],['phone',390,844],['phone-landscape',844,390],['desktop',1440,900]]){
  await p.setViewportSize({width,height});await p.emulateMedia({reducedMotion:'reduce'});await p.evaluate(()=>window.scrollTo(0,0));await p.waitForFunction(()=>Math.abs(document.querySelector('.dcu-footer').getBoundingClientRect().bottom-innerHeight)<2);await p.waitForFunction(()=>getComputedStyle(document.querySelector('.passage')).opacity==='1');
  const d=await p.evaluate(()=>{const root=document.querySelector('.dcu-root'),foot=document.querySelector('.dcu-footer').getBoundingClientRect(),next=document.querySelector('#next').getBoundingClientRect(),menu=document.querySelector('#cbtToggleMenu').getBoundingClientRect(),left=document.querySelector('#leftaction').getBoundingClientRect(),right=document.querySelector('#rightaction').getBoundingClientRect();return{overflow:root.scrollWidth>root.clientWidth+2,left:foot.left,right:foot.right,bottom:foot.bottom,innerWidth,innerHeight,nextLeft:next.left,menuRight:menu.right,menuNextOverlap:Math.min(menu.right,next.right)-Math.max(menu.left,next.left)>1&&Math.min(menu.bottom,next.bottom)-Math.max(menu.top,next.top)>1,groupsAligned:Math.abs(left.left-right.left)<2,controls:document.querySelectorAll('#next').length}});
  assert.equal(d.overflow,false,name);assert.ok(d.left>=-1&&d.right<=width+1,name+' dock bounds');assert.equal(d.menuNextOverlap,false,name+' menu/next overlap');assert.ok(d.groupsAligned);assert.equal(d.controls,1);layouts.push({name,...d});await p.screenshot({animations:'disabled',path:path.join(__dirname,'artifacts',name+'.png'),fullPage:true});
 }
 // Theme and expanded menu at phone size.
 await p.setViewportSize({width:390,height:844});
 await p.getByText('离开战斗',{exact:true}).click();await p.waitForFunction(()=>!document.querySelector('.dcu-shell'));await p.getByText('返回训练场',{exact:true}).click();await p.waitForSelector('.dcu-shell');await p.evaluate(()=>DoLCombatUI.destroy());assert.equal(await p.locator('.dcu-root').count(),0);assert.equal(await p.locator('#next').count(),1);assert.equal(await p.locator('#next').evaluate(e=>getComputedStyle(e).position),'fixed');await p.locator('#leftaction label').filter({hasText:'防御'}).click();assert.equal(await p.evaluate(()=>V.leftaction),'guard');assert.equal(await p.locator('.error').count(),0);assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(__dirname,'artifacts','release-verification.json'),JSON.stringify({version:require('../package.json').version,passed:true,scope:'Neutral SugarCube fixture; original generateCombatAction; no real save or Android test',layouts},null,2));console.log('PASS dense native actions, single native dock, menu, shortcut selector, node identity/state, replacement/restore, list controls, 5 viewports, theme, cleanup.');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
