// Pass the target Mod's opt-main.js; its actual description-edit handler runs on fake saves.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require('playwright'),{buildSync}=require('esbuild');
const root=path.resolve(__dirname,'..'),folder=path.join(root,'compat/dol-optimization-soft-wet');
const optSource=fs.readFileSync(process.argv[2]||'', 'utf8');
const start=optSource.indexOf('initsave: async function() {'),end=optSource.indexOf('setTitleWithBlur: function(',start);
assert.ok(start>=0&&end>start,'Known target method missing');
const method=optSource.slice(start,end).trim().replace(/,$/,'');
const engine=buildSync({entryPoints:[path.join(root,'src/runtime/ui.ts')],bundle:true,write:false,format:'iife',globalName:'UiRuntimeModule'}).outputFiles[0].text;
const row=(id,extra='',hidden='')=>`<div class="savesListRow ${id===2?'dgs-native-row':''}" ${hidden}><div class="saveGroup"><div class="saveId">${id}</div><div class="saveButton"><button data-action="save">保存</button><button data-action="load">读取</button></div><div class="saveName">fixture</div><div class="saveDetails"><span>original description</span><span class="datestamp">date</span>${extra}</div></div><button class="deleteButton" data-action="delete">删除</button></div>`;
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('http://optimization.test/',route=>route.fulfill({contentType:'text/html',body:`<html data-dol-midnight><body><div id="customOverlay" data-overlay="saves"><div id="overlayTabs"></div><div id="saveList"><section class="dgs-host"><div class="dgs-layout"><aside class="dgs-list"><div class="dgs-entries"><button>proxy</button></div><div class="dgs-list-tools"><button id="fixture-page-prev">previous</button><input id="pageNum" type="number" value="1"><button id="fixture-page-next">next</button><input id="pageLen" value="10"></div></aside></div></section><div id="saves-list-container"><div class="savesListRow dgs-native-row"><div class="saveGroup"><div class="saveId">#</div></div></div>${row(1,'<span class="future-extension">unknown extension</span>')}${row(2)}${row(3,'','hidden')}</div></div></div><button id="outside">outside</button></body></html>`}));
 await page.goto('http://optimization.test/');
 await page.locator('#saves-list-container').evaluate((n,html)=>n.insertAdjacentHTML('beforeend',html),row('A').replace('<button data-action="save">保存</button>',''));
 await page.addStyleTag({content:'.dgs-native-row{display:none!important}.hidden,[hidden]{display:none}.savesListRow{max-height:2.4em!important}.saveDetails>span{white-space:nowrap!important}'});
 await page.evaluate(()=>{
  window.calls={save:0,load:0,delete:0,settings:0};window.savesEnabled=true;window.version='1.1.1.2';
  window.modUtils={getMod:n=>n==='原版优化'?{version}:null};
  window.idb={getItem:async id=>id===1?{data:{delta:[{variables:{saveName:'fixture',startDate:0,timeStamp:1}}]}}:null};
  window.DateTime=class{constructor(){Object.assign(this,{year:2022,month:1,day:1,hour:8,minute:0,weekDayName:'fixture'})}};
  window.getTimeString=()=> '08:00';
  window.$=target=>({one(type,callback){(typeof target==='string'?[...document.querySelectorAll(target)]:[target]).forEach(n=>n.addEventListener(type.split('.')[0],callback,{once:true}))}});
  window.SugarCube={Dialog:{setup(){},wiki(html){document.getElementById('fixture-dialog')?.remove();const d=document.createElement('div');d.id='fixture-dialog';d.innerHTML=html;document.body.append(d)},open(){},close(){document.getElementById('fixture-dialog')?.remove();document.dispatchEvent(new Event(':dialogclose'))}}};
  document.querySelectorAll('[data-action]').forEach(n=>n.onclick=()=>calls[n.dataset.action]++);
 });
 await page.addScriptTag({content:`window.DolOptimization={data:{customdesc:{}},saveSettings(){calls.settings++},${method},setTitleWithBlur(title,text){title.textContent=text}};`});
 await page.evaluate(()=>DolOptimization.initsave());
 await page.evaluate(()=>{window.nodes=[...document.querySelectorAll('#saveList *')].map(n=>({n,parent:n.parentNode,next:n.nextSibling,click:n.onclick,value:n.value}));window.beforeOpt=JSON.stringify(DolOptimization.data);window.beforeSettings=calls.settings});
 await page.addScriptTag({content:engine});
 await page.evaluate(()=>{window.runtime=UiRuntimeModule.createUiRuntime(window,()=>({}));window.DoLGameUI={ui:runtime.api,getPreferences:()=>({savesEnabled})}});
 await page.addStyleTag({content:fs.readFileSync(path.join(folder,'dol-optimization-soft-wet.css'),'utf8')});
 const script=buildSync({entryPoints:[path.join(folder,'dol-optimization-soft-wet.ts')],bundle:true,write:false,format:'iife',target:'es2022'}).outputFiles[0].text;await page.addScriptTag({content:script});
 assert.equal(await page.evaluate(()=>DolOptimizationSoftWet.getDiagnostics().match),'full');
 // The game reuses this overlay root; an attribute-only menu transition must be rediscovered.
 await page.evaluate(()=>document.getElementById('customOverlay').dataset.overlay='options');
 await page.waitForFunction(()=>!document.querySelector('[data-dgu-adapter="DolOptimizationSoftWet"]'));
 await page.evaluate(()=>document.getElementById('customOverlay').dataset.overlay='saves');
 await page.waitForFunction(()=>DolOptimizationSoftWet.getDiagnostics().match==='full');
 assert.equal(await page.locator('.dgs-entries').isVisible(),false);
 assert.equal(await page.locator('.savesListRow').nth(2).isVisible(),true,'Empty native slot restored');
 assert.equal(await page.locator('.future-extension').isVisible(),true);
 const summaryStyles=await page.locator('.saveDetails>span:first-child').evaluateAll(nodes=>nodes.filter(n=>['A','1'].includes(n.closest('.saveGroup').querySelector('.saveId').textContent.trim())).map(n=>({whiteSpace:getComputedStyle(n).whiteSpace,maxHeight:getComputedStyle(n).maxHeight,overflow:getComputedStyle(n).overflow})));
 assert.equal(summaryStyles.length,2);assert.deepEqual(summaryStyles[0],summaryStyles[1]);assert.equal(summaryStyles[0].whiteSpace,'normal');assert.equal(summaryStyles[0].overflow,'auto');
 assert.equal(await page.locator('.savesListRow[hidden]').isVisible(),false);
 assert.ok(await page.locator('.savesListRow').nth(1).evaluate(n=>n.getBoundingClientRect().height>=n.querySelector('.saveGroup').getBoundingClientRect().height),'Card grows with original content');
 assert.equal(await page.evaluate(()=>nodes.every(x=>x.n.parentNode===x.parent&&x.n.nextSibling===x.next&&x.n.onclick===x.click&&x.n.value===x.value)),true);
 await page.locator('[data-action=load]').first().click();assert.equal(await page.evaluate(()=>calls.load),1);
 await page.locator('.saveTitle').click();await page.locator('.saveTitleInput').fill('cancelled fixture note');await page.locator('#outside').click();
 await page.locator('#customdesc-cancel').click();assert.equal(await page.locator('.saveTitle').innerText(),'original description');
 assert.equal(await page.evaluate(()=>calls.settings===beforeSettings),true);assert.equal(await page.evaluate(()=>JSON.stringify(DolOptimization.data)===beforeOpt),true);
 assert.equal(await page.locator('.datestamp>.pink').count(),1,'Target-provided in-game date retained');
 await page.locator('.saveTitle').click();await page.locator('.saveTitleInput').fill('confirmed fixture note');await page.locator('#outside').click();await page.locator('#customdesc-ok').click();
 assert.equal(await page.locator('.saveTitle').innerText(),'confirmed fixture note');
 assert.deepEqual(await page.evaluate(()=>DolOptimization.data.customdesc[1]),{desc:'confirmed fixture note',timestamp:1});
 assert.equal(await page.evaluate(()=>calls.settings===beforeSettings+1),true);assert.equal(await page.evaluate(()=>calls.save+calls.delete),0);
 // Target defect also reproduces with the adapter removed: initialization appends, not replaces, dates.
 await page.evaluate(()=>DolOptimization.initsave());assert.equal(await page.locator('.datestamp>.pink').count(),2);
 await page.evaluate(()=>DolOptimizationSoftWet.destroy());await page.evaluate(()=>DolOptimization.initsave());
 assert.equal(await page.locator('.datestamp>.pink').count(),3,'Repeated dates originate in target initializer');
 await page.addScriptTag({content:script});
 const refresh=()=>page.evaluate(()=>DoLGameUI.ui.rescan());
 await page.evaluate(()=>{savesEnabled=false});await refresh();assert.equal(await page.locator('[data-dgu-adapter]').count(),0);
 await page.evaluate(()=>{savesEnabled=true;version='future'});await refresh();assert.equal(await page.locator('.dgs-entries').isVisible(),true,'Unknown version unchanged');
 await page.evaluate(()=>{version='1.1.1.2';document.getElementById('pageLen').remove()});await refresh();assert.equal(await page.locator('.dgs-entries').isVisible(),true,'Missing critical structure unchanged');
 await page.evaluate(()=>{document.querySelector('.dgs-list-tools').insertAdjacentHTML('beforeend','<input id="pageLen" value="10">');document.documentElement.removeAttribute('data-dol-midnight')});await refresh();assert.equal(await page.locator('[data-dgu-adapter]').count(),0);
 await page.evaluate(()=>document.documentElement.setAttribute('data-dol-midnight',''));await refresh();
 await page.setViewportSize({width:560,height:900});assert.equal(await page.locator('#saves-list-container').evaluate(n=>getComputedStyle(n).gridTemplateColumns.split(' ').length),1);
 await page.evaluate(()=>DolOptimizationSoftWet.destroy());assert.equal(await page.locator('[data-dgu-adapter]').count(),0);
 await page.evaluate(()=>{delete window.DoLGameUI});await page.addScriptTag({content:script});assert.equal(await page.evaluate(()=>DolOptimizationSoftWet.getDiagnostics().reason),'runtime-unavailable');
 assert.deepEqual(errors,[]);console.log('PASS: native structure/events, actual target description cancel/confirm on fake saves, dates, hidden/unknown content, gate/fallback, narrow layout and cleanup');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
