const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{const p=await b.newPage(),errors=[],network=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(/^https?:/.test(r.url()))network.push(r.url())});await p.goto(pathToFileURL(path.join(__dirname,'../docs/EYES_SAVE_DEMO.html')).href);
 for(const width of [390,1363]){await p.setViewportSize({width,height:876});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.ok(await p.locator('button').evaluateAll(es=>es.filter(e=>e.getBoundingClientRect().width>0).every(e=>e.offsetHeight>=44)));assert.equal(await p.locator('.stable').first().evaluate(e=>getComputedStyle(e).backdropFilter),'none')}
 assert.equal(await p.locator('.entry').count(),5);await p.locator('#search').fill('雨后');assert.equal(await p.locator('.entry').count(),1);await p.locator('.entry').click();assert.equal(await p.locator('#detail-name').textContent(),'雨后的街角');await p.locator('#search').fill('');
 await p.locator('#create').click();assert.equal(await p.locator('.entry').count(),6);await p.locator('#save').click();assert.match(await p.locator('#detail-date').textContent(),/刚刚/);await p.locator('#load').click();assert.match(await p.locator('#notice').textContent(),/未读取任何游戏存档/);
 await p.locator('#delete').click();await p.locator('#cancel').click();assert.equal(await p.locator('.entry').count(),6);await p.locator('#delete').click();await p.locator('#delete-confirm').click();assert.equal(await p.locator('.entry').count(),5);assert.equal(await p.locator('.entry[aria-pressed=true]').evaluate(e=>e===document.activeElement),true);
 await p.locator('#close-detail').click();assert.equal(await p.locator('#detail').isVisible(),false);await p.locator('.entry').first().click();assert.equal(await p.locator('#detail').isVisible(),true);
 await p.reload();assert.equal(await p.locator('.entry').count(),5);assert.deepEqual(network,[]);assert.deepEqual(errors,[]);console.log('PASS save demo: narrow/wide layout, solid text, search/select, memory-only create/save/load/delete/cancel, focus, reload reset, no HTTP requests');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
