const {chromium}=require('playwright'),assert=require('assert/strict'),{buildSync}=require('esbuild');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{
 const p=await b.newPage({viewport:{width:390,height:500}});
 const caption='<div id="statmeters">Status</div><br><span class="gold">小贴士：</span>A quiet tip.<br><br><span id="alert">Immediate warning</span><div id="overlayButtons"><button id="save">Save</button><button id="foreign">Mod</button><button id="dmc-sidebar-button">Center</button><button id="dol-midnight-sidebar-button">Settings</button></div>';
 await p.setContent('<div id="ui-bar"><div id="storyCaptionContent">'+caption+'</div></div>');
 const html=await p.locator('#ui-bar').innerHTML();
 await p.evaluate(()=>{window.nodes=[...document.querySelectorAll('#ui-bar *')];window.clicks=0;document.getElementById('dmc-sidebar-button').onclick=()=>clicks++});
 await p.evaluate(()=>{window.entryMoves=0;window.entryOwner=new MutationObserver(()=>{const parent=document.getElementById('overlayButtons');for(const id of ['dmc-sidebar-button','dol-midnight-sidebar-button']){const button=document.getElementById(id);if(button.parentElement!==parent){entryMoves++;parent.append(button)}}});entryOwner.observe(document.getElementById('overlayButtons'),{childList:true,subtree:true})});
 await p.addScriptTag({content:buildSync({entryPoints:['src/theme/layout.ts'],bundle:true,write:false,format:'iife',globalName:'LayoutTest'}).outputFiles[0].text});
 await p.evaluate(()=>{LayoutTest.startLayout();DMTLayout.sync({enabled:true,layout:true})});
 await p.waitForTimeout(200);assert.equal(await p.evaluate(()=>entryMoves),0,'entry maintenance must not compete with sidebar layout');assert.equal(await p.locator('.dmt-system-tools').count(),1);
 assert.equal(await p.locator('#overlayButtons>#dmc-sidebar-button').count(),1,'entry owner direct-parent contract');assert.equal(await p.locator('#overlayButtons>#dol-midnight-sidebar-button').count(),1);
 assert.equal(await p.locator('.dmt-sidebar-tip').count(),1);assert.equal(await p.locator('#alert').isVisible(),true);
 assert.equal(await p.locator('.dmt-sidebar-tip').evaluate(e=>e.open),false);
 await p.locator('.dmt-sidebar-tip>summary').click();assert.equal(await p.locator('.dmt-sidebar-tip>div').textContent(),'A quiet tip.');
 await p.locator('#dmc-sidebar-button').click();assert.equal(await p.evaluate(()=>clicks),1);
 assert.equal(await p.locator('#save').isVisible(),true);assert.equal(await p.locator('#foreign').isVisible(),true);
 assert.equal(await p.evaluate(()=>nodes.every(n=>n.isConnected)),true);
 await p.evaluate(()=>DMTLayout.sync({enabled:true,layout:false}));assert.equal(await p.locator('#ui-bar').innerHTML(),html,'exact native order and nodes restored');
 await p.evaluate(()=>DMTLayout.sync({enabled:true,layout:true}));
 await p.locator('#storyCaptionContent').evaluate((e,caption)=>e.innerHTML=caption,caption);
 await p.waitForSelector('.dmt-sidebar-tip');assert.equal(await p.locator('.dmt-system-tools').count(),1,'native redraw receives one region');
 await p.evaluate(()=>DMTLayout.destroy());assert.equal(await p.locator('#ui-bar').innerHTML(),html);
 await p.locator('#storyCaptionContent').evaluate(e=>e.innerHTML='<div id="statmeters"></div><br><span class="gold">Mod warning</span>Do not fold<br>');
 await p.evaluate(()=>{LayoutTest.startLayout();DMTLayout.sync({enabled:true,layout:true})});assert.equal(await p.locator('.dmt-sidebar-tip').count(),0,'unknown caption remains native');
 await p.evaluate(()=>entryOwner.disconnect());
 console.log('PASS sidebar disclosure, direct native tools, dynamic redraw, exact fallback/destroy, unknown warning boundary');
 }finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
