const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs'),{pathToFileURL}=require('node:url');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{
 const p=await b.newPage({viewport:{width:390,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.emulateMedia({reducedMotion:'reduce'});await p.goto(pathToFileURL(path.join(__dirname,'fixture.html')).href);await p.waitForSelector('#listContainer');
 await p.addStyleTag({path:path.join(__dirname,'../dist/game-ui.css')});await p.addScriptTag({path:path.join(__dirname,'../dist/game-ui.js')});await p.waitForFunction(()=>!!window.DoLGameUI);
 assert.equal(await p.evaluate(()=>typeof window.DoLRuntime),'undefined');
 await p.evaluate(()=>{Object.assign(V,{pain:0,tiredness:2,stress:3,trauma:4,control:5});window.beforeStatus=JSON.stringify(V)});
 await p.evaluate(()=>DoLGameUI.openSettings());await p.locator('.dmt-debug > summary').click();await p.getByLabel('状态接口预览（实验）',{exact:true}).check();await p.waitForFunction(()=>document.querySelector('#dol-status-preview').textContent.includes('疼痛：0'));assert.equal(await p.evaluate(()=>JSON.stringify(V)===beforeStatus),true);assert.equal(await p.evaluate(()=>DoLRuntime.status.v1.getSnapshot().status),'ready');
 await p.evaluate(()=>DoLMidnightTheme.setPreference('wideReading',true));await p.evaluate(()=>new Promise(requestAnimationFrame));assert.equal(await p.locator('#dol-status-preview').evaluate(e=>!e.hidden&&e.textContent.includes('疼痛：0')),true,'Vue preference update preserves service-owned preview');
 await p.evaluate(()=>{window.statusApi=DoLRuntime.status.v1;window.statusCalls=[];window.unsubStatus=statusApi.subscribe(s=>statusCalls.push(s));});await p.waitForFunction(()=>statusCalls.length>0);
 await p.evaluate(()=>{statusCalls.length=0;V.pain=23;statusApi.refresh();statusApi.refresh();statusApi.refresh()});await p.waitForFunction(()=>statusCalls.length===1);assert.equal(await p.evaluate(()=>statusCalls[0].values.pain),23);
 await p.evaluate(()=>{window.previousState=SugarCube.State.variables;jQuery.event.trigger(':onloadsave',{save:{mustNotRead:true}})});assert.equal(await p.evaluate(()=>statusApi.getSnapshot().status),'loading');assert.equal(await p.evaluate(()=>statusApi.getSnapshot().values.pain),null);
 await p.evaluate(()=>SugarCube.Engine.play('Arena'));await p.waitForFunction(()=>statusApi.getSnapshot().status==='ready');assert.equal(await p.evaluate(()=>SugarCube.State.variables===previousState),false);await p.evaluate(()=>{V.pain=31;statusApi.refresh()});await p.waitForFunction(()=>document.querySelector('#dol-status-preview').textContent.includes('疼痛：31'));assert.equal(await p.evaluate(()=>previousState.pain),23);
 await p.evaluate(()=>{delete V.trauma;V.stress=NaN;statusApi.refresh()});await p.waitForFunction(()=>document.querySelector('#dol-status-preview').textContent.includes('创伤：不可用'));assert.equal(await p.evaluate(()=>statusApi.getSnapshot().values.stress),null);
 await p.screenshot({path:path.join(__dirname,'artifacts','status-preview-phone.png'),animations:'disabled'});
 await p.getByLabel('状态接口预览（实验）',{exact:true}).uncheck();assert.equal(await p.evaluate(()=>typeof window.DoLRuntime),'undefined');assert.equal(await p.evaluate(()=>statusApi.getSnapshot().status),'disposed');await p.evaluate(()=>{window.statusCountAfterOff=statusCalls.length;jQuery.event.trigger(':passageend');statusApi.refresh()});await p.evaluate(()=>new Promise(requestAnimationFrame));assert.equal(await p.evaluate(()=>statusCalls.length),await p.evaluate(()=>statusCountAfterOff));
 // Do not overwrite another provider using the public namespace.
 await p.evaluate(()=>{window.foreignStatus={marker:true};window.DoLRuntime={status:{v1:foreignStatus}}});await p.getByLabel('状态接口预览（实验）',{exact:true}).check();assert.equal(await p.evaluate(()=>DoLRuntime.status.v1===foreignStatus),true);await p.evaluate(()=>{delete window.DoLRuntime;DoLStatusPreview.setEnabled(true)});assert.equal(await p.evaluate(()=>typeof DoLRuntime.status.v1.getSnapshot),'function');await p.getByLabel('状态接口预览（实验）',{exact:true}).uncheck();assert.equal(await p.evaluate(()=>typeof window.DoLRuntime),'undefined');
 await p.getByLabel('状态接口预览（实验）',{exact:true}).check();await p.evaluate(()=>DoLGameUI.destroy());assert.equal(await p.evaluate(()=>typeof window.DoLRuntime),'undefined');assert.equal(await p.locator('#dol-midnight-controls').count(),0);assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(__dirname,'artifacts','status-verification.json'),JSON.stringify({passed:true,api:'DoLRuntime.status.v1',scope:'Synthetic neutral SugarCube state only; load invalidation event simulated, no actual save import or device test',checks:['opt-in default','no state writes','current State replacement','zero and unavailable values','one notification per frame','load invalidation','disable/dispose','namespace preservation','settings preview']},null,2));console.log('PASS status adapter and preview in real SugarCube: lifecycle, current state, opt-in, cleanup and namespace protection.');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
