const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require('playwright'),{buildSync}=require('esbuild');
const root=path.resolve(__dirname,'..');
const engine=buildSync({entryPoints:[path.join(root,'src/runtime/ui.ts')],bundle:true,write:false,format:'iife',globalName:'UiRuntimeModule'}).outputFiles[0].text;
const read=name=>fs.readFileSync(path.join(root,name),'utf8');
const compile=name=>buildSync({entryPoints:[path.join(root,name)],bundle:true,write:false,format:'iife',target:'es2022'}).outputFiles[0].text;
const adapter=mod=>compile(`compat/${mod}-soft-wet/${mod}-soft-wet.ts`);
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const errors=[];
 async function page(html){const p=await browser.newPage({viewport:{width:1280,height:900}});p.on('pageerror',e=>errors.push(e.message));await p.route('http://ui-runtime.test/',r=>r.fulfill({contentType:'text/html',body:html}));await p.goto('http://ui-runtime.test/');return p}
 const settle=p=>p.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
 let p=await page('<html data-dol-midnight data-dgu-visual="1" data-dgu-visualGlass data-dgu-visualMotion><body><main id="foreign-area"></main><div data-surface="test"><div id="toolbar"></div><input data-proof="native" value="untouched"><button id="action">native</button><span class="future" hidden>unknown</span></div></body></html>');
 await p.evaluate(()=>{
  window.observed=[];const Original=MutationObserver;
  window.MutationObserver=class extends Original{observe(node,options){observed.push({node:node===document.body?'body':node.id||node.tagName,...options});super.observe(node,options)}};
  window.themePrefs={visualTier:1};window.versions={Target:'1.0',Other:'1.0'};window.modUtils={getMod:name=>versions[name]?{version:versions[name]}:null};
  window.native=document.querySelector('[data-proof]');window.nativeParent=native.parentNode;window.nativeNext=native.nextSibling;window.calls=0;document.querySelector('#action').onclick=()=>calls++;
 });
 await p.addScriptTag({content:engine});
 await p.evaluate(()=>{
  window.runtime=UiRuntimeModule.createUiRuntime(window,()=>themePrefs);window.ui=runtime.api;
  window.spec={id:'Example',version:'1',target:{name:'Target',versions:['1.0']},scope:['#missing-scope','[data-surface="test"]'],fingerprint:{id:'test-v1',safe:[['#toolbar']],required:[['#missing-input','[data-proof="native"]']]},roles:[{role:'page-shell',selectors:[':scope'],safe:true},{role:'toolbar',selectors:['#toolbar'],safe:true},{role:'card',selectors:['#missing-input','[data-proof="native"]']}]};
  window.handle=ui.registerStyleAdapter(spec);
 });
 assert.equal(await p.evaluate(()=>handle.getDiagnostics().status),'active');
 // Inspector snapshots never read native business state, node text or input values.
 await p.addStyleTag({content:read('dist/game-ui.css')});
 await p.evaluate(()=>{window.StartConfig={version:'0.5.12.13'};window.SugarCube={State:{passage:'Test Page',get variables(){throw Error('Forbidden business read')}}};window.V={password:'private-game-secret'};native.value='private-input-secret';window.DoLGameUI={version:'2.1.0'};modUtils.version='2.101.1'});
 const diagnostics=await p.evaluate(()=>ui.getDiagnostics());
 assert.equal(diagnostics.gameVersion,'0.5.12.13');assert.equal(diagnostics.loaderVersion,'2.101.1');assert.equal(diagnostics.page.name,'Test Page');
 assert.equal(JSON.stringify(diagnostics).includes('private-'),false);assert.equal(JSON.stringify(diagnostics).includes('data-proof="native"'),false,'attribute values redacted from export');
 assert.equal(diagnostics.adapters[0].mappings.find(x=>x.role==='card').fallback,true);
 assert.equal(await p.evaluate(()=>{const d=ui.getDiagnostics();return Object.isFrozen(d)&&Object.isFrozen(d.events)&&Object.isFrozen(d.adapters[0].mappings[0].tags)&&Object.isFrozen(d.capabilities)}),true);
 await p.evaluate(()=>{window.inspector=ui.openInspector();window.sameInspector=ui.openInspector()});
 assert.equal(await p.evaluate(()=>inspector===sameInspector),true);assert.equal(await p.locator('.dgu-inspector').count(),1);
 await p.getByRole('button',{name:'重新扫描',exact:true}).click();assert.equal(await p.locator('.dgu-inspector [role=status]').innerText(),'已重新检测注册的 Adapter。');
 await p.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{window.copiedDiagnostics=text}}}));
 await p.getByRole('button',{name:'复制诊断',exact:true}).click();await p.waitForFunction(()=>!!window.copiedDiagnostics);
 assert.equal(await p.evaluate(()=>JSON.parse(copiedDiagnostics).schemaVersion),1);assert.equal(await p.evaluate(()=>copiedDiagnostics.includes('private-')),false);
 const downloadPromise=p.waitForEvent('download');await p.getByRole('button',{name:'导出 JSON',exact:true}).click();const download=await downloadPromise;
 assert.equal(download.suggestedFilename(),'soft-wet-ui-diagnostics.json');const exported=JSON.parse(fs.readFileSync(await download.path(),'utf8'));assert.equal(exported.page.name,'Test Page');
 await p.evaluate(()=>{navigator.clipboard.writeText=async()=>{throw Error('denied')}});await p.getByRole('button',{name:'复制诊断',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.dgu-inspector [role=status]').textContent.includes('操作不可用'));
 await p.keyboard.press('Escape');assert.equal(await p.locator('.dgu-inspector').count(),0);
 await p.evaluate(()=>{for(let i=0;i<45;i++){versions.Target=i%2?'1.0':'unknown';handle.refresh()}versions.Target='1.0';handle.refresh();window.eventCount=ui.getDiagnostics().events.length;for(let i=0;i<5;i++)ui.rescan()});
 assert.equal(await p.evaluate(()=>ui.getDiagnostics().events.length),32,'event buffer bounded');assert.equal(await p.evaluate(()=>eventCount===ui.getDiagnostics().events.length),true,'stable rescan creates no duplicate events');
 assert.equal(await p.evaluate(()=>handle.getDiagnostics().selectors.filter(x=>x.fallback).length),3);
 assert.equal(await p.evaluate(()=>{const monitor=new MutationObserver(()=>{});monitor.observe(document.querySelector('[data-surface]'),{attributes:true,subtree:true});handle.refresh();const count=monitor.takeRecords().length;monitor.disconnect();return count}),0,'unchanged refresh must not rewrite style attributes');
 assert.equal(await p.evaluate(()=>observed.filter(x=>x.node==='body').every(x=>!x.subtree)),true,'no global body subtree observation');
 assert.equal(await p.evaluate(()=>Object.isFrozen(ui)&&Object.isFrozen(ui.getCapabilities())&&Object.isFrozen(ui.getTheme().tokens)&&Object.isFrozen(handle.getDiagnostics().selectors)),true);
 assert.equal(await p.evaluate(()=>ui.getVisualTier()),'Balanced');
 await p.evaluate(()=>{themePrefs.visualTier=2;document.documentElement.setAttribute('data-dgu-visual','2')});await settle(p);
 assert.equal(await p.evaluate(()=>ui.getCapabilities().visualTier),'Fancy');
 await p.evaluate(()=>{window.savedValue=native.value;window.second=ui.registerStyleAdapter({...spec,id:'Other',target:{name:'Other',versions:['1.0']},scope:['#other'],when:()=>{throw Error('UI probe fault')}});document.body.insertAdjacentHTML('beforeend','<div id="other"><div id="toolbar"></div></div>')});await settle(p);
 assert.equal(await p.evaluate(()=>second.getDiagnostics().status),'failed');assert.equal(await p.evaluate(()=>handle.getDiagnostics().status),'active');
 await p.evaluate(()=>{versions.Target='1.1';handle.refresh()});
 assert.equal(await p.evaluate(()=>handle.getDiagnostics().status),'partial');assert.equal(await p.evaluate(()=>native.hasAttribute('data-dgu-role')),false,'unverified version gets only verified safe roles');
 await p.evaluate(()=>{versions.Target='1.0';native.removeAttribute('data-proof');handle.refresh()});
 assert.equal(await p.evaluate(()=>handle.getDiagnostics().reason),'structure-drift');
 await p.evaluate(()=>{native.setAttribute('data-proof','native');nativeParent.append(native.cloneNode());handle.refresh()});
 assert.equal(await p.evaluate(()=>handle.getDiagnostics().status),'partial','ambiguous critical selector cannot fully match');
 await p.evaluate(()=>{nativeParent.lastChild.remove();document.querySelector('[data-surface] #toolbar').remove();handle.refresh()});
 assert.equal(await p.evaluate(()=>handle.getDiagnostics().status),'unknown');assert.equal(await p.locator('[data-dgu-adapter="Example"]').count(),0);
 await p.evaluate(()=>{nativeParent.insertAdjacentHTML('afterbegin','<div id="toolbar"></div>');handle.refresh();document.documentElement.removeAttribute('data-dol-midnight')});await settle(p);
 assert.equal(await p.locator('[data-dgu-adapter]').count(),0);assert.equal(await p.evaluate(()=>ui.getCapabilities().enabled||ui.getCapabilities().glass||ui.getCapabilities().motion),false);
 await p.evaluate(()=>document.documentElement.setAttribute('data-dol-midnight',''));await settle(p);
 assert.equal(await p.evaluate(()=>native===document.querySelector('[data-proof]')&&native.parentNode===nativeParent&&native.nextSibling===nativeNext&&native.value===savedValue),true);
 await p.locator('#action').click();assert.equal(await p.evaluate(()=>calls),1);assert.equal(await p.locator('.future[hidden]').count(),1);
 assert.equal(await p.evaluate(()=>{try{ui.registerStyleAdapter({...spec,id:'Invalid',scope:['[']});return false}catch{return true}}),true);
 assert.equal(await p.evaluate(()=>{try{ui.registerStyleAdapter(spec);return false}catch{return true}}),true);
 await p.evaluate(()=>{runtime.destroy();runtime.destroy();document.querySelector('[data-surface]').append(document.createElement('button'))});await settle(p);
 assert.equal(await p.locator('[data-dgu-adapter],[data-dgu-role]').count(),0);assert.equal(await p.evaluate(()=>handle.getDiagnostics().status),'disposed');assert.equal(await p.evaluate(()=>ui.getAdapterDiagnostics().length),0);await p.close();

 // Request surfaces own only new content; native dialog owns focus and stacking.
 p=await page('<html data-dol-midnight data-dgu-visual="1" data-dgu-visualGlass data-dgu-visualMotion><body><button id="opener">open</button><div id="original"><input id="original-input" value="native"></div></body></html>');
 await p.addStyleTag({content:read('dist/game-ui.css')});await p.addScriptTag({content:engine});
 await p.evaluate(()=>{window.runtime=UiRuntimeModule.createUiRuntime(window,()=>({visualTier:1}));window.ui=runtime.api;window.closeReasons=[];window.request=()=>{const content=document.createElement('section');content.innerHTML='<label>New field <input value="caller" autofocus></label><span hidden>unknown</span><button>New action</button>';return {id:'ExampleModal',title:'Example',content,onClose:reason=>closeReasons.push(reason)}};document.querySelector('#opener').focus();window.nativeInput=document.querySelector('#original-input');window.nativeParent=nativeInput.parentNode;window.options=request();window.handle=ui.openModal(options);window.newInput=options.content.querySelector('input');window.newClicks=0;options.content.querySelector('button').onclick=()=>newClicks++});
 assert.equal(await p.evaluate(()=>ui.getCapabilities().surfaces&&Object.isFrozen(handle)),true);
 assert.equal(await p.locator('.dgu-surface').evaluate(d=>getComputedStyle(d,'::backdrop').backdropFilter),'blur(24px)');
 assert.equal(await p.locator('.dgu-surface').evaluate(d=>getComputedStyle(d).backdropFilter),'none','native backdrop is the single blur surface');
 assert.equal(await p.evaluate(()=>document.activeElement===newInput),true,'caller autofocus is retained');
 for(let i=0;i<5;i++){await p.keyboard.press('Shift+Tab');assert.equal(await p.evaluate(()=>document.querySelector('.dgu-surface').contains(document.activeElement)||document.activeElement===document.body),true,'native dialog leaves background controls inert; browser chrome may take focus')}
 await p.evaluate(()=>nativeInput.focus());assert.notEqual(await p.evaluate(()=>document.activeElement.id),'original-input','background input cannot receive focus');
 assert.equal(await p.evaluate(()=>ui.openModal(options)===handle),true,'duplicate keeps original handle and content');
 assert.equal(await p.evaluate(()=>{try{ui.openDrawer(options);return false}catch{return true}}),true,'a duplicate cannot change kind');
 await p.locator('.dgu-surface-content button').click();assert.equal(await p.evaluate(()=>newClicks),1);
 await p.locator('.dgu-surface-content input').fill('edited');
 await p.evaluate(()=>{options.id='mutated-after-open';window.child=ui.openDrawer({...request(),id:'ChildDrawer',title:'Details'})});
 assert.equal(await p.locator('.dgu-surface[open]').count(),2);await p.keyboard.press('Escape');
 assert.equal(await p.evaluate(()=>handle.isOpen()&&!child.isOpen()),true,'Escape closes only upper surface');
 await p.evaluate(()=>{handle.close();handle.close()});
 assert.equal(await p.evaluate(()=>document.activeElement.id),'opener');assert.equal(await p.locator('.dgu-surface').count(),0);
 assert.deepEqual(await p.evaluate(()=>closeReasons),['escape','api']);assert.equal(await p.evaluate(()=>options.content.parentNode===null&&newInput.value==='edited'),true,'caller content detached intact');
 await p.evaluate(()=>{window.handle=ui.openModal(request())});await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>closeReasons.at(-1)),'escape');
 await p.evaluate(()=>{window.handle=ui.openModal(request())});await p.getByRole('button',{name:'关闭浮层',exact:true}).click();assert.equal(await p.evaluate(()=>closeReasons.at(-1)),'button');
 await p.evaluate(()=>{window.handle=ui.openModal(request())});
 const box=await p.locator('.dgu-surface').boundingBox();await p.mouse.move(box.x+box.width/2,box.y+box.height/2);await p.mouse.down();await p.mouse.move(2,2);await p.mouse.up();assert.equal(await p.evaluate(()=>handle.isOpen()),true,'dragging from inside is not a backdrop click');
 await p.mouse.click(2,2);assert.equal(await p.evaluate(()=>closeReasons.at(-1)),'backdrop');
 await p.evaluate(()=>{const form=document.createElement('form');form.method='dialog';const button=document.createElement('button');button.textContent='Native submit';form.append(button);window.submits=0;form.addEventListener('submit',()=>submits++);window.handle=ui.openModal({...request(),content:form})});
 await p.getByRole('button',{name:'Native submit',exact:true}).click();assert.equal(await p.evaluate(()=>submits),1);assert.equal(await p.evaluate(()=>closeReasons.at(-1)),'native','native submit behavior is not proxied');
 await p.evaluate(()=>{window.disableOptions=request();window.handle=ui.openModal(disableOptions);document.documentElement.removeAttribute('data-dol-midnight')});
 assert.equal(await p.evaluate(()=>ui.openModal(disableOptions)),null,'disabled theme cannot reuse a still-open handle');await settle(p);
 assert.equal(await p.evaluate(()=>closeReasons.at(-1)),'disabled');assert.equal(await p.evaluate(()=>ui.openModal(request())),null);assert.equal(await p.locator('.dgu-surface').count(),0);
 await p.evaluate(()=>document.documentElement.setAttribute('data-dol-midnight',''));
 assert.equal(await p.evaluate(()=>{try{ui.openModal({...request(),content:nativeInput});return false}catch{return true}}),true,'existing original nodes cannot be moved');
 assert.equal(await p.evaluate(()=>nativeInput.parentNode===nativeParent&&nativeInput.value==='native'),true);
 await p.evaluate(()=>{window.showModal=HTMLDialogElement.prototype.showModal;HTMLDialogElement.prototype.showModal=()=>{throw Error('unavailable')}});
 assert.equal(await p.evaluate(()=>ui.openModal(request())),null);assert.equal(await p.evaluate(()=>closeReasons.at(-1)),'failed');assert.equal(await p.locator('.dgu-surface').count(),0);
 await p.evaluate(()=>{HTMLDialogElement.prototype.showModal=undefined});assert.equal(await p.evaluate(()=>ui.getCapabilities().surfaces),false);assert.equal(await p.evaluate(()=>ui.openDrawer(request())),null);
 await p.evaluate(()=>{HTMLDialogElement.prototype.showModal=showModal});
 await p.evaluate(()=>{window.handle=ui.openDrawer({...request(),onClose:()=>{throw Error('caller close failed')}});handle.close();window.handle=ui.openModal(request());runtime.destroy();runtime.destroy()});
 assert.equal(await p.evaluate(()=>closeReasons.at(-1)),'destroyed');assert.equal(await p.locator('.dgu-surface').count(),0);
 await p.close();

 // Real adapter scripts bind before Core, then survive Core teardown/restart.
 const hub='<div id="customOverlay" data-overlay="modloader"><div id="customOverlayTitle"><div id="overlayTabs" class="modhub-modloader-tabs"><button>管理</button></div></div><div id="customOverlayContent"><div id="modHubModManageContainer" class="modhub-container"><div class="modhub-sticky-toolbar"><input id="setting" type="checkbox"></div><ul class="modhub-list"><li class="modhub-item"><button id="native-button">操作</button><span hidden>unknown</span></li></ul></div></div></div>';
 p=await page('<html><body><div id="passages"></div>'+hub+'</body></html>');
 await p.evaluate(()=>{window.versions={ModHub:'1.3.0',maplebirch:'5.2.3'};window.modUtils={getMod:name=>versions[name]?{version:versions[name]}:null};window.V={unchanged:'game'};window.beforeV=JSON.stringify(V);window.calls=0;window.nativeButton=document.querySelector('#native-button');nativeButton.onclick=()=>calls++;window.nativeSetting=document.querySelector('#setting');window.nativeParent=nativeButton.parentNode;window.nativeNext=nativeButton.nextSibling;window.changeCalls=0;nativeSetting.onchange=()=>changeCalls++});
 for(const mod of ['modhub','maplebirch']){await p.addStyleTag({content:read(`compat/${mod}-soft-wet/${mod}-soft-wet.css`)});await p.addScriptTag({content:adapter(mod)})}
 assert.equal(await p.locator('[data-dgu-adapter]').count(),0,'without Core, optional packages do nothing');
 await p.evaluate(()=>{window.DoLGameUI={ui:{apiVersion:1}};document.dispatchEvent(new Event('dol-ui-runtime-ready'))});assert.equal(await p.evaluate(()=>ModHubSoftWet.getDiagnostics().reason),'runtime-api-unsupported');
 await p.evaluate(()=>{window.DoLGameUI={ui:{apiVersion:1,getCapabilities:()=>({styleAdapters:false}),registerStyleAdapter:()=>{throw Error('must not register')}}};document.dispatchEvent(new Event('dol-ui-runtime-ready'))});assert.equal(await p.evaluate(()=>MapleBirchSoftWet.getDiagnostics().reason),'style-adapter-unavailable');
 await p.evaluate(()=>delete window.DoLGameUI);
 const inject=async()=>{await p.addStyleTag({content:read('dist/game-ui.css')});await p.addScriptTag({content:read('dist/game-ui.js')});await settle(p)};
 await inject();assert.equal(await p.evaluate(()=>DoLGameUI.version),JSON.parse(read('package.json')).version);assert.equal(await p.evaluate(()=>ModHubSoftWet.getDiagnostics().status),'active');
 assert.equal(await p.evaluate(()=>ModHubSoftWet.getDiagnostics().degraded),false,'absent optional marketplace role is not a downgrade of a full management-page match');
 await p.addStyleTag({content:read('examples/ui-surfaces/surface-demo.css')});await p.addScriptTag({content:compile('examples/ui-surfaces/surface-demo.ts')});
 await p.evaluate(()=>window.demo=SoftWetSurfaceDemo.openModal());await p.locator('[data-demo-control]').check();await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>SoftWetSurfaceDemo.getLastClose()),'escape');
 await p.evaluate(()=>window.demo=SoftWetSurfaceDemo.openDrawer());
 for(const width of [390,1280]){await p.setViewportSize({width,height:900});await settle(p);assert.equal(await p.locator('.dgu-surface').evaluate(d=>{const b=d.getBoundingClientRect();return b.left>=0&&b.right<=innerWidth+1&&b.bottom<=innerHeight+1&&d.scrollWidth<=d.clientWidth+1}),true,'drawer stays readable within narrow/wide viewport')}
 await p.getByRole('button',{name:'关闭浮层',exact:true}).click();assert.equal(await p.evaluate(()=>SoftWetSurfaceDemo.getLastClose()),'button');
 assert.equal(await p.locator('.modhub-item[data-dgu-role="compact-row"]').count(),1);
 await p.locator('#native-button').click();await p.locator('#setting').check();assert.deepEqual(await p.evaluate(()=>[calls,changeCalls]),[1,1]);
 await p.evaluate(()=>DoLGameUI.setPreference('enabled',false));await settle(p);assert.equal(await p.locator('[data-dgu-adapter]').count(),0);
 assert.equal(await p.evaluate(()=>SoftWetSurfaceDemo.openModal()),null);
 assert.equal(await p.evaluate(()=>nativeButton.isConnected&&nativeButton.parentNode===nativeParent&&nativeButton.nextSibling===nativeNext&&nativeSetting.checked),true);
 await p.evaluate(()=>DoLGameUI.setPreference('enabled',true));await settle(p);assert.equal(await p.evaluate(()=>ModHubSoftWet.getDiagnostics().status),'active');
 await p.evaluate(()=>{document.querySelector('#customOverlayContent').insertAdjacentHTML('beforeend','<p id="mod-unknown">new extension</p>');document.querySelector('#modHubModManageContainer').classList.remove('modhub-container')});await settle(p);
 assert.equal(await p.evaluate(()=>ModHubSoftWet.getDiagnostics().status),'partial');assert.equal(await p.locator('.modhub-item[data-dgu-role]').count(),0);assert.equal(await p.locator('#mod-unknown').isVisible(),true);
 assert.equal(await p.evaluate(()=>ModHubSoftWet.getDiagnostics().degraded),true);
 await p.evaluate(()=>{const overlay=document.querySelector('#customOverlay');overlay.dataset.overlay='saves';document.querySelector('#customOverlayTitle').innerHTML='<div id="overlayTabs"><button>云存档</button></div>';document.querySelector('#customOverlayContent').innerHTML='<div id="maplebirch-cloud-save" class="maplebirch-cloud-save"><div class="settingsToggleItemWide"><input data-cloud-save-field="endpoint" value="native"><input data-cloud-save-field="token" value="secret"><select id="native-select"><option value="a">A</option></select><div class="maplebirch-cloud-save-actions"><button>connect</button></div></div></div>'});await settle(p);
 assert.equal(await p.evaluate(()=>MapleBirchSoftWet.getDiagnostics().status),'active');assert.equal(await p.locator('[data-dgu-adapter="ModHubSoftWet"]').count(),0);
 await p.evaluate(()=>{window.cloudNodes=[...document.querySelectorAll('#maplebirch-cloud-save *')].map(n=>({n,parent:n.parentNode}));document.querySelector('#native-select').append(new Option('Mod choice','new'));DoLSavesUI.setEnabled(false)});await settle(p);
 assert.equal(await p.locator('[data-dgu-adapter="MapleBirchSoftWet"]').count(),0);await p.evaluate(()=>DoLSavesUI.setEnabled(true));await settle(p);
 assert.equal(await p.evaluate(()=>cloudNodes.every(x=>x.n.isConnected&&x.n.parentNode===x.parent)),true);assert.equal(await p.locator('#native-select option').count(),2);
 assert.equal(await p.evaluate(()=>JSON.stringify(DoLGameUI.ui.getAdapterDiagnostics()).includes('secret')),false);
 assert.equal(await p.evaluate(()=>JSON.stringify(DoLGameUI.ui.getDiagnostics()).includes('secret')),false);
 await p.evaluate(()=>{DoLGameUI.openSettings()});await p.locator('details.dmt-debug summary').click();await p.getByRole('button',{name:'Runtime Inspector',exact:true}).click();
 assert.equal(await p.locator('.dgu-inspector').count(),1,'advanced settings entry opens Inspector');
 await p.evaluate(()=>DoLGameUI.setPreference('enabled',false));await settle(p);assert.equal(await p.locator('.dgu-inspector').count(),0);assert.equal(await p.evaluate(()=>DoLGameUI.ui.openInspector()),null);
 await p.evaluate(()=>{DoLGameUI.setPreference('enabled',true);document.querySelector('#dol-midnight-controls')?.close()});
 await p.evaluate(()=>DoLGameUI.destroy());await settle(p);assert.equal(await p.locator('[data-dgu-adapter],[data-dgu-role]').count(),0);await inject();
 assert.equal(await p.evaluate(()=>MapleBirchSoftWet.getDiagnostics().status),'active','independent package rebinds to new Core');
 await p.evaluate(()=>MapleBirchSoftWet.destroy());await settle(p);assert.equal(await p.locator('[data-dgu-adapter="MapleBirchSoftWet"]').count(),0);assert.equal(await p.evaluate(()=>DoLGameUI.ui.getAdapterDiagnostics().length),1);
 assert.equal(await p.evaluate(()=>JSON.stringify(V)===beforeV),true);assert.deepEqual(errors,[]);await p.close();
 console.log('PASS UI runtime: readonly Inspector/export/privacy/bounded events, native surfaces, scoped adapters/fallback/rollback/restart and unchanged native business state');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
