const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs'),{pathToFileURL}=require('node:url');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{
 const p=await b.newPage({viewport:{width:1704,height:1136}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.emulateMedia({reducedMotion:'reduce'});
 const url=pathToFileURL(path.join(__dirname,'fixture.html')).href;
 const inject=async()=>{await p.addStyleTag({path:path.join(__dirname,'../dist/game-ui.css')});await p.addScriptTag({path:path.join(__dirname,'../dist/game-ui.js')});await p.waitForFunction(()=>!!window.DoLGameUI)};
 await p.goto(url);await p.waitForSelector('#listContainer');await p.evaluate(()=>{localStorage.setItem('DoLMidnightTheme.preferences.v1',JSON.stringify({enabled:false,comfortable:false,wideReading:true,showCompact:true}));localStorage.setItem('DoLCombatUI.enabled.v1','false')});await inject();
 assert.equal(await p.evaluate(()=>DoLGameUI.getPreferences().wardrobePaged),true,'new installs use paged wardrobe');
 await p.evaluate(()=>DoLGameUI.setPreference('wardrobePaged',false));await p.reload();await p.waitForSelector('#listContainer');await inject();
 assert.equal(await p.evaluate(()=>DoLGameUI.getPreferences().wardrobePaged),false,'saved opt-out survives upgrade and reload');
 await p.evaluate(()=>DoLGameUI.setPreference('wardrobePaged',true));
 assert.equal(await p.locator('.dcu-shell').count(),0);assert.equal(await p.evaluate(()=>DoLGameUI.getPreferences().enabled),false);assert.equal(await p.evaluate(()=>DoLGameUI.getPreferences().wideReading),true);assert.equal(await p.locator('#dol-midnight-compact-button').count(),0);
 await p.evaluate(()=>DoLGameUI.openSettings());await p.getByLabel('启用炭黑主题',{exact:true}).check();await p.getByLabel('启用新版战斗界面',{exact:true}).check();await p.waitForSelector('.dcu-shell');assert.equal(await p.evaluate(()=>localStorage.getItem('DoLCombatUI.enabled.v1')),'true');
 await p.keyboard.press('Escape');assert.equal(await p.locator('dialog[open]').count(),0);
 await p.getByRole('button',{name:'原版界面 ↗',exact:true}).click();await p.evaluate(()=>DoLGameUI.openSettings());assert.equal(await p.getByLabel('启用新版战斗界面',{exact:true}).isChecked(),false);assert.equal(await p.getByLabel('启用炭黑主题',{exact:true}).isChecked(),true);
 await p.getByLabel('启用新版战斗界面',{exact:true}).check();await p.evaluate(()=>window.dispatchEvent(new Event('backbutton')));assert.equal(await p.locator('dialog[open]').count(),0);
 await p.evaluate(()=>DoLGameUI.openSettings());assert.equal(await p.getByLabel('衣柜按页渲染',{exact:true}).isChecked(),true);assert.equal(await p.getByLabel('商店离屏绘制延后（实验）',{exact:true}).isChecked(),false);await p.getByLabel('衣柜按页渲染',{exact:true}).check();await p.getByLabel('商店离屏绘制延后（实验）',{exact:true}).check();await p.keyboard.press('Escape');
 // The optional shop page experiment is hidden without its mod, then appears when the API arrives.
 assert.equal(await p.getByLabel('商店按页生成（实验）',{exact:true}).count(),0);await p.evaluate(()=>{window.DoLShopPageExperiment={enabled:false,calls:[],setEnabled(value){this.enabled=value;this.calls.push(value)}};DoLGameUI.openSettings()});await p.getByLabel('商店按页生成（实验）',{exact:true}).check();assert.deepEqual(await p.evaluate(()=>window.DoLShopPageExperiment.calls),[false,true]);assert.match(await p.getByRole('status').textContent(),/下次进入或重建/);assert.equal(await p.evaluate(()=>DoLGameUI.getPreferences().shopPageExperiment),true);await p.keyboard.press('Escape');await p.evaluate(()=>{delete window.DoLShopPageExperiment;DoLGameUI.openSettings()});assert.equal(await p.getByLabel('商店按页生成（实验）',{exact:true}).count(),0);await p.keyboard.press('Escape');await p.evaluate(()=>{window.DoLShopPageExperiment={enabled:false,calls:[],setEnabled(value){this.enabled=value;this.calls.push(value)}};DoLGameUI.openSettings()});assert.equal(await p.getByLabel('商店按页生成（实验）',{exact:true}).count(),1);assert.deepEqual(await p.evaluate(()=>window.DoLShopPageExperiment.calls),[true]);await p.keyboard.press('Escape');await p.evaluate(()=>{window.DoLShopPageExperiment={setEnabled(){throw new Error('unsupported')}};DoLGameUI.openSettings()});assert.equal(await p.getByLabel('商店按页生成（实验）',{exact:true}).count(),0);assert.match(await p.getByRole('status').textContent(),/不可用/);await p.keyboard.press('Escape');
 // Duplicate script inclusion must not add another manager, dock, or dialog.
 await p.addScriptTag({path:path.join(__dirname,'../dist/game-ui.js')});assert.equal(await p.locator('.dcu-shell').count(),1);assert.equal(await p.locator('#dol-midnight-controls').count(),1);assert.equal(await p.locator('#dol-midnight-sidebar-button').count(),1);
 const sizes=[[390,844],[844,390],[1704,1136],[1136,1704],[1440,900]];
 for(const [width,height]of sizes){await p.setViewportSize({width,height});await p.evaluate(()=>DoLGameUI.openSettings());const r=await p.locator('#dol-midnight-controls').evaluate(e=>{const r=e.getBoundingClientRect();return{left:r.left,right:r.right,top:r.top,bottom:r.bottom,overflow:e.scrollWidth>e.clientWidth+1}});assert.ok(r.left>=0&&r.right<=width+1&&r.top>=0&&r.bottom<=height+1,JSON.stringify(r));assert.equal(r.overflow,false);await p.screenshot({path:path.join(__dirname,'artifacts',`settings-${width}x${height}.png`)});await p.keyboard.press('Escape')}
 await p.reload();await p.waitForSelector('#listContainer');await inject();assert.equal(await p.evaluate(()=>DoLGameUI.getPreferences().combatEnabled),true);assert.equal(await p.evaluate(()=>DoLGameUI.getPreferences().enabled),true);
 assert.equal(await p.evaluate(()=>DoLGameUI.getPreferences().wardrobePaged&&DoLGameUI.getPreferences().shopDeferredPaint),true);assert.equal(await p.evaluate(()=>DoLGameUI.getPreferences().shopPageExperiment),true);
 await p.evaluate(()=>{window.DoLShopPageExperiment={enabled:false,calls:[],setEnabled(value){this.enabled=value;this.calls.push(value)}};DoLGameUI.openSettings()});await p.getByRole('button',{name:'回退原版界面',exact:true}).click();assert.equal(await p.evaluate(()=>DoLGameUI.getPreferences().wardrobePaged||DoLGameUI.getPreferences().shopDeferredPaint),false);assert.equal(await p.evaluate(()=>DoLGameUI.getPreferences().shopPageExperiment),false);assert.deepEqual(await p.evaluate(()=>window.DoLShopPageExperiment.calls),[true,false]);await p.getByRole('button',{name:'启用新版界面',exact:true}).click();await p.keyboard.press('Escape');
 await p.evaluate(()=>DoLGameUI.destroy());assert.equal(await p.locator('.dcu-root,#dol-midnight-controls,#dol-midnight-sidebar-button,#dmt-drawer-shade').count(),0);assert.equal(await p.locator('#next').evaluate(e=>getComputedStyle(e).position),'fixed');assert.equal(await p.evaluate(()=>document.documentElement.hasAttribute('data-dol-midnight')),false);
 // Existing old modules loaded first can be cleanly handed over.
 await p.addScriptTag({path:path.resolve(__dirname,'../../../mods/midnight-theme/layout.js')});await p.addScriptTag({path:path.resolve(__dirname,'../../../mods/midnight-theme/theme.js')});await p.addScriptTag({path:path.resolve(__dirname,'../../../frontend/combat-ui/dist/combat-ui.js')});await p.waitForSelector('.dcu-shell');await inject();assert.equal(await p.locator('.dcu-root').count(),1);assert.equal(await p.locator('#dol-midnight-controls').count(),1);assert.equal(await p.locator('#dol-midnight-sidebar-button').textContent(),'界面设置');await p.evaluate(()=>DoLGameUI.destroy());assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(__dirname,'artifacts','unified-verification.json'),JSON.stringify({passed:true,version:require('../package.json').version,checks:['old preferences retained','independent toggles','classic/settings synchronization','Escape/backbutton','repeat injection','five modal viewports','reload persistence','destroy restoration','old modules loaded first handover'],realGame:false,android:false},null,2));console.log('PASS unified settings, persistence, independent toggles, five dialog viewports, duplicate guard and lifecycle handover.');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
