const assert=require('node:assert/strict'),vm=require('node:vm'),path=require('node:path'),{buildSync}=require('esbuild');
const code=buildSync({entryPoints:[path.join(__dirname,'../src/wardrobe/slot-mappings.ts')],bundle:true,platform:'node',format:'cjs',write:false}).outputFiles[0].text;
const moduleObject={exports:{}};vm.runInNewContext(code,{module:moduleObject,exports:moduleObject.exports});
let version='4.1.1';const registry=moduleObject.exports.createSlotMappings(()=>version);
const item={name:'coat'},inventory={over_upper:[item]},worn={over_upper:{name:'naked'}},definitions={over_upper:[item]};
const snapshot={inventory,worn,setup:{clothes:definitions},variables:{debug:false}};
const before=JSON.stringify(snapshot),spec={id:'ReOverfits',target:{name:'ReOverfits',versions:['4.1.1']},slots:{over_upper:'外套上装'}};
const handle=registry.register(spec);spec.slots.over_upper='mutated';spec.target.versions[0]='4.2.0';
assert.equal(registry.labels(snapshot).over_upper,'外套上装');assert.equal(JSON.stringify(snapshot),before);assert.equal(inventory.over_upper[0],item);
version='4.2.0';assert.equal(registry.labels(snapshot).over_upper,undefined);version='4.1.1';
assert.equal(registry.labels({...snapshot,inventory:{}}).over_upper,undefined);
assert.equal(registry.labels({...snapshot,worn:{}}).over_upper,undefined);
assert.equal(registry.labels({...snapshot,setup:{clothes:{over_upper:[]}}}).over_upper,undefined);
assert.throws(()=>registry.register({...spec,id:'Other'}),/already mapped/);
assert.throws(()=>registry.register({...spec,id:'ReOverfits'}),/duplicate/);
assert.throws(()=>registry.register({...spec,id:'Core',slots:{upper:'override'}}),/Invalid wardrobe slot/);
assert.throws(()=>registry.register({...spec,id:'Reserved',slots:JSON.parse('{"__proto__":"bad"}')}),/Invalid wardrobe slot/);
handle.destroy();handle.destroy();assert.equal(registry.labels(snapshot).over_upper,undefined);
registry.register({...spec,target:{name:'ReOverfits',versions:['4.1.1']}});registry.destroy();assert.equal(registry.labels(snapshot).over_upper,undefined);
assert.throws(()=>registry.register(spec),/disposed/);
const ranges=moduleObject.exports.createSlotMappings(()=>version,{getSemVerTools:()=>({parseVersion:v=>({version:v}),parseRange:r=>r,satisfies:(v,r)=>r==='>=4.1.1'&&['4.1.1','4.2.0'].includes(v)})});
const ranged=ranges.register({...spec,target:{name:'ReOverfits',versions:['>=4.1.1']}});
for(const v of ['4.1.1','4.2.0']) {version=v;assert.equal(ranges.labels(snapshot).over_upper,'mutated')}
assert.equal(ranges.labels({...snapshot,inventory:{}}).over_upper,undefined);
version='4.1.0';assert.equal(ranges.labels(snapshot).over_upper,undefined);ranged.destroy();version='4.2.0';assert.equal(ranges.labels(snapshot).over_upper,undefined);
console.log('PASS semantic mapping: target/data gates, no state mutation, input copy, collision guards, revoke/dispose');
// Fresh slot names exercise discovery independently of the three ReOverfits mappings.
let detected='1.0.0';const fresh=moduleObject.exports.createSlotMappings(()=>detected);
const extra={inventory:{cape:[item],charm:[]},worn:{cape:{name:'naked'},charm:{name:'naked'}},setup:{clothes:{cape:[item],charm:[item]}},variables:{debug:false}};
const original=JSON.stringify(extra);
assert.deepEqual(Array.from(fresh.support(extra),s=>s.reason),['registration-required','registration-required']);
assert.ok(fresh.support(extra).every(s=>!s.canDisplay&&s.operationContract==='unreviewed'));
const optIn=fresh.register({id:'FreshSlots',target:{name:'FreshSlots',versions:['1.0.0']},slots:{cape:'披肩'}});
const supported=fresh.support(extra),cape=supported.find(s=>s.slot==='cape');
assert.equal(cape.reason,'mapped');assert.equal(cape.operationContract,'author-declared-native');assert.ok(cape.canDisplay);
assert.ok(Object.isFrozen(supported)&&supported.every(Object.isFrozen));assert.equal(JSON.stringify(extra),original);
detected='2.0.0';assert.equal(fresh.support(extra).find(s=>s.slot==='cape').reason,'unsupported-version');
detected=undefined;assert.equal(fresh.support(extra).find(s=>s.slot==='cape').reason,'target-not-detected');
detected='1.0.0';assert.equal(fresh.support({...extra,worn:{}}).find(s=>s.slot==='cape').reason,'missing-native-data');
assert.equal(fresh.support(null)[0].reason,'wardrobe-unavailable');
optIn.destroy();assert.equal(fresh.support(extra).find(s=>s.slot==='cape').reason,'registration-required');fresh.destroy();assert.equal(fresh.support(extra).length,0);
console.log('PASS fresh-slot discovery: empty slot, opt-in contract, immutable diagnostics, missing/version/revoke boundaries');
