// M2 candidate check in an isolated original 0.5.11.9 browser game.
const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const project=path.resolve('E:/daima/DoL'),out=path.join(__dirname,'artifacts/m2-20261008/browser');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{const route=decodeURIComponent(new URL(req.url,'http://localhost').pathname),file=route==='/game'?path.join(project,'releases/source-baseline-0.5.11.9/vanilla.html'):path.join(project,'upstream/game-0.5.11.9',route);if(!file.startsWith(project)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);res.end();return}fs.createReadStream(file).pipe(res)});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true});const result={environment:'isolated original DoL 0.5.11.9 / Edge',checks:[],errors:[]};try{
const p=await browser.newPage({viewport:{width:1363,height:900}});p.on('pageerror',e=>result.errors.push(e.message));await p.addInitScript(()=>localStorage.setItem('verifiedAge','true'));await p.goto(`http://127.0.0.1:${server.address().port}/game`,{waitUntil:'load',timeout:90000});await p.waitForFunction(()=>window.SugarCube?.State?.variables?.options,{timeout:60000});await p.evaluate(()=>SugarCube.Engine.play('Start2'));await p.waitForLoadState('networkidle');
await p.evaluate(()=>{V.location='home';V.lastWardrobeSlot='upper';V.wardrobe_location='wardrobe';V.options.images=0;for(const d of setup.clothes.upper.filter(c=>c.name!=='naked'&&!c.outfitPrimary&&!c.outfitSecondary).slice(0,3)){const item=structuredClone(d);item.colour=item.colour_options?.[0]??0;item.accessory_colour=item.accessory_colour_options?.[0]??0;V.wardrobe.upper.push(item)}SugarCube.Engine.play('Wardrobe')});
await p.addStyleTag({path:'E:/daima/DoL/publish/DoL-Game-UI/dist/game-ui.css'});await p.addScriptTag({path:'E:/daima/DoL/publish/DoL-Game-UI/dist/game-ui.js'});await p.waitForSelector('.dgw-shell');await p.screenshot({path:path.join(out,'baseline.png')});
await p.evaluate(()=>{window.originalList=document.querySelector('#wardrobeList');window.preferencesBefore=DoLGameUI.getPreferences();DoLGameUI.destroy();window.originalContracts=['#wardrobeExits','#listoutfits','#warmth-description'].map(sel=>document.querySelector(sel)).filter(Boolean).map(node=>({node,parent:node.parentNode,previous:node.previousSibling,next:node.nextSibling,onclick:node.onclick}));window.m1PreviewObservers=new Set();const OriginalResizeObserver=ResizeObserver;window.ResizeObserver=class extends OriginalResizeObserver{observe(target,options){super.observe(target,options);if(target.matches?.(".dgw-root"))m1PreviewObservers.add(this)}disconnect(){super.disconnect();m1PreviewObservers.delete(this)}}});await p.addStyleTag({path:path.join(__dirname,'../dist/game-ui.css')});await p.addScriptTag({path:path.join(__dirname,'../dist/game-ui.js')});await p.waitForSelector('.dgw-candidate');
assert.equal(await p.evaluate(()=>m1PreviewObservers.size),1);assert.equal(await p.evaluate(()=>DoLGameUI.ui.apiVersion),1);assert.deepEqual(await p.evaluate(()=>DoLGameUI.getPreferences()),await p.evaluate(()=>preferencesBefore));result.checks.push('API v1 and preferences retained');
await p.evaluate(()=>{const list=document.querySelector('#wardrobeList');window.unknownNode=document.createElement('p');unknownNode.id='m1-unknown-native';unknownNode.textContent='Unknown Mod information';list.after(unknownNode);window.wornBefore=JSON.stringify(V.worn);});
await p.locator('.dgw-browse-mode input').check();await p.locator('.dgw-item').first().click();await p.waitForSelector('.dgw-selected-detail');assert.equal(await p.evaluate(()=>JSON.stringify(V.worn)),await p.evaluate(()=>wornBefore),'browse must not equip');assert.equal(await p.locator('.dgw-item[aria-pressed=true]').count(),1);
await p.locator('.dgw-open-original').click();assert.ok(await p.locator('#m1-unknown-native').isVisible());assert.ok(await p.evaluate(()=>document.querySelector('#wardrobeList')===originalList));await p.locator('.dgw-open-original').click();result.checks.push('browse has no business mutation; original unknown content is visible on request');
await p.screenshot({path:path.join(out,'m2-wide.png')});
await p.evaluate(()=>document.querySelector('.dgw-root').style.width='550px');await p.waitForTimeout(100);const layout=await p.evaluate(()=>{const root=document.querySelector('.dgw-root'),i=document.querySelector('.dgw-inventory'),d=document.querySelector('.dgw-selected-detail');return {viewport:innerWidth,container:root.clientWidth,columns:getComputedStyle(document.querySelector('.dgw-workspace')).gridTemplateColumns,inventory:i.getBoundingClientRect().toJSON(),detail:d.getBoundingClientRect().toJSON(),overflow:root.scrollWidth>root.clientWidth+2}});assert.ok(layout.container===550&&layout.viewport>900);assert.ok(layout.detail.top>=layout.inventory.top);assert.ok(await p.locator('.dgw-items .dgw-selected-detail').count()===1);assert.equal(layout.overflow,false);result.layout=layout;await p.screenshot({path:path.join(out,'m2-container550.png')});result.checks.push('550px container reorganizes at wide viewport with no horizontal overflow');
const expected=await p.evaluate(()=>{const index=Number(document.querySelector('.dgw-item').dataset.key.split(':')[1]);return V.wardrobe.upper[index].variable});await p.locator('.dgw-explicit-wear').click();await p.waitForFunction(v=>V.worn.upper.variable===v,expected);result.checks.push('explicit wear verified by original V.worn.upper');
await p.locator('.dgw-browse-mode input').uncheck();const quick=await p.evaluate(()=>{const index=Number(document.querySelector('.dgw-item').dataset.key.split(':')[1]);return V.wardrobe.upper[index].variable});await p.locator('.dgw-item').first().click();await p.waitForFunction(v=>V.worn.upper.variable===v,quick);result.checks.push('default one-click wear verified by original state');
// Existing public slot mapping, controlled metadata only; not a real ReOverfits load.
await p.evaluate(()=>{window.modUtils={getMod:n=>n==='M1Fixture'?{version:'1.0.0'}:undefined};const d={...setup.clothes.upper[1],variable:'m1-over',name:'M1 coat',description:'Controlled extension description'};setup.clothes.over_upper=[{name:'naked'},d];V.wardrobe.over_upper=[structuredClone(d)];V.worn.over_upper={name:'naked'};window.mapping=DoLGameUI.wardrobe.registerSlotMapping({id:'M1Fixture',target:{name:'M1Fixture',versions:['1.0.0']},slots:{over_upper:'外套上装'}})});
await p.locator('.dgw-slots button').filter({hasText:'外套上装'}).click();await p.locator('.dgw-browse-mode input').check();await p.locator('.dgw-item').first().click();assert.match(await p.locator('.dgw-selected-detail').textContent(),/Controlled extension description/);assert.equal(await p.locator('.dgw-category-note').count(),0);
result.checks.push('controlled extension fixture is not counted as live Mod business proof');
if(process.env.DOL_REOVERFITS_DEFINITIONS){
 const definitionProof=JSON.parse(fs.readFileSync(process.env.DOL_REOVERFITS_DEFINITIONS,'utf8'));
 await p.evaluate(definitions=>{
  mapping.destroy();window.modUtils={getMod:n=>n==='ReOverfitsFixture'?{version:'4.1.1'}:undefined};
  for(const [slot,list]of Object.entries(definitions)){setup.clothes[slot]=list;V.wardrobe[slot]=[];V.worn[slot]=structuredClone(list[0])}
  const primary=definitions.over_upper.find(d=>d.outfitPrimary?.over_head&&d.outfitPrimary?.over_lower);
  window.realFixturePieces={over_upper:structuredClone(primary)};
  for(const [slot,name]of Object.entries(primary.outfitPrimary))realFixturePieces[slot]=structuredClone(definitions[slot].find(d=>d.name===name));
  for(const [slot,item]of Object.entries(realFixturePieces)){item.colour='green';item.accessory_colour=0;V.wardrobe[slot].push(item)}
  window.mapping=DoLGameUI.wardrobe.registerSlotMapping({id:'ReOverfitsFixture',target:{name:'ReOverfitsFixture',versions:['4.1.1']},slots:{over_head:'外层头饰',over_upper:'外套上装',over_lower:'外套下装'}});
 },definitionProof.result.definitions);
 await p.locator('.dgw-slots button').filter({hasText:'外套上装'}).click();await p.locator('.dgw-item').click();
 assert.equal(await p.locator('.dgw-selected-detail h3').textContent(),await p.evaluate(()=>realFixturePieces.over_upper.cn_name_cap??realFixturePieces.over_upper.name_cap));
 assert.ok(await p.locator('.dgw-selected-detail').textContent().then(x=>x.includes(definitionProof.result.definitions.over_upper[1].description)));
 await p.evaluate(()=>{window.staleWearButton=document.querySelector('.dgw-explicit-wear');DoLWardrobeUI.performance.setEnabled(true);DoLWardrobeUI.performance.reset()});await p.locator('.dgw-explicit-wear').click();await p.waitForFunction(()=>Object.entries(realFixturePieces).every(([slot,item])=>V.worn[slot].name===item.name));await p.evaluate(()=>staleWearButton.click());assert.equal(await p.evaluate(()=>DoLWardrobeUI.performance.report().phases['native.wear'].samples),1,'detached stale detail cannot replay original wear');await p.evaluate(()=>DoLWardrobeUI.performance.setEnabled(false));
 result.reoverfits={scope:'controlled nonempty fixture using definitions read from actual Android Mod; original 0.5.11.9 macros, not full Mod load in browser',fullSetWear:await p.evaluate(()=>Object.entries(realFixturePieces).map(([slot,item])=>({slot,expected:item.variable,worn:V.worn[slot].variable,inWardrobe:V.wardrobe[slot].includes(item)})))};
 result.checks.push('real ReOverfits definitions in isolated fixture: detail and original full-set wear');
}

await p.evaluate(()=>DoLWardrobeUI.setEnabled(false));await p.waitForFunction(()=>!document.querySelector('.dgw-shell'));assert.ok(await p.locator('#m1-unknown-native').isVisible());assert.ok(await p.evaluate(()=>document.querySelector('#wardrobeList')===originalList));assert.equal(await p.evaluate(()=>m1PreviewObservers.size),0);result.checks.push('disable restores same original list and visible unknown node; preview Observer disposed');
await p.evaluate(()=>{window.savedWardrobe=V.wardrobe;Object.defineProperty(V,'wardrobe',{configurable:true,get(){throw Error('M1 controlled source fault')}});DoLWardrobeUI.setEnabled(true)});await p.waitForTimeout(100);assert.equal(await p.locator('.dgw-shell').count(),0);assert.ok(await p.locator('#m1-unknown-native').isVisible());await p.evaluate(()=>{Object.defineProperty(V,'wardrobe',{configurable:true,writable:true,value:savedWardrobe})});assert.equal(await p.evaluate(()=>m1PreviewObservers.size),0);result.checks.push('controlled source failure keeps original content available');await p.evaluate(()=>DoLWardrobeUI.setEnabled(true));await p.waitForSelector('.dgw-candidate');assert.equal(await p.evaluate(()=>m1PreviewObservers.size),1);for(let i=0;i<6;i++){await p.evaluate(()=>{DoLWardrobeUI.setEnabled(false);DoLWardrobeUI.setEnabled(true)});await p.waitForSelector('.dgw-candidate');assert.equal(await p.evaluate(()=>m1PreviewObservers.size),1)}await p.evaluate(()=>DoLWardrobeUI.setEnabled(false));await p.waitForFunction(()=>!document.querySelector('.dgw-candidate'));assert.equal(await p.evaluate(()=>m1PreviewObservers.size),0);result.checks.push('remount has exactly one preview Observer, unmount has zero');
await p.evaluate(()=>DoLGameUI.destroy());assert.ok(await p.evaluate(()=>originalContracts.every(c=>c.node.isConnected&&c.node.parentNode===c.parent&&c.node.previousSibling===c.previous&&c.node.nextSibling===c.next&&c.node.onclick===c.onclick)));result.checks.push('native parent/sibling/handler contracts restored after core destroy');assert.equal(result.errors.length,0);result.status='passed';console.log(JSON.stringify(result));
}catch(e){result.status='failed';result.failure=e.stack;throw e}finally{fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(result,null,2));await browser.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
