const assert=require('node:assert/strict'),path=require('node:path'),vm=require('node:vm'),{buildSync}=require('esbuild');
const built=buildSync({entryPoints:[path.join(__dirname,'../src/wardrobe/icons.ts')],bundle:true,write:false,format:'cjs',platform:'node'}),m={exports:{}};
vm.runInNewContext(built.outputFiles[0].text,{module:m,exports:m.exports});const {clothingIconLayers:icons}=m.exports;
const normalise=s=>s.replace(/ /g,'-');
const d={name:'school shirt',iconFile:1,accIcon:0,accessory:0,colour_options:['white','black']};
let result=icons({colour:'black'},d,normalise);assert.equal(result[0].src,'img/misc/icon/clothes/school-shirt.png');assert.match(result[0].className,/icon-black/);
assert.equal(icons({colour:'black'},{...d,colour_options:['black']},normalise)[0].className,'icon');
assert.equal(icons({colour:'custom',colourCustom:'filter: hue-rotate(45deg);'},d,normalise)[0].style,'filter:hue-rotate(45deg)');
assert.equal(icons({colour:'custom',colourCustom:'filter: blur(0) url(https://example.com)'},d,normalise)[0].style,'');
assert.equal(icons({pattern:'dots'},{...d,iconFile:'pattern'},normalise)[0].src,'img/misc/icon/clothes/school-shirt-dots.png');
result=icons({colour:0,accessory_colour:'black'},{...d,accIcon:1,accessory:1,accessory_colour_options:['black','white']},normalise);assert.equal(result.length,2);assert.equal(result[1].src,'img/misc/icon/clothes/school-shirt-acc.png');assert.match(result[1].className,/icon-black/);
assert.equal(icons({},null,normalise).length,0);
assert.equal(icons({},{...d,iconFile:'../escape.png'},normalise).length,0);
console.log('PASS icon paths, colour restrictions, custom filters, patterns, accessory layers, missing definitions');
