const assert=require('node:assert/strict'),vm=require('node:vm'),path=require('node:path'),{buildSync}=require('esbuild');
const code=buildSync({entryPoints:[path.join(__dirname,'../src/wardrobe/source.ts')],bundle:true,platform:'node',format:'cjs',write:false}).outputFiles[0].text;
const moduleObject={exports:{}};vm.runInNewContext(code,{module:moduleObject,exports:moduleObject.exports});
const definition={name:'coat',variable:'coat',description:'native description',warmth:5,integrity_max:100},item={...definition,integrity:80,type:['formal'],colour:'blue'};
const root={V:{location:'home',wardrobe_location:'wardrobe',wardrobe:{upper:[item],mystery:[item],space:20},worn:{upper:{name:'naked'},mystery:{name:'naked'}},options:{images:0},wardrobeDefaults:{showTraits:true}},setup:{clothes:{upper:[definition],mystery:[definition]},colourName:()=> 'blue'}};
let current=true;const source=moduleObject.exports.createWardrobeSource(root,()=>({upper:'上装'}),()=>current);
const before=JSON.stringify(root.V),first=source.read('upper'),key=first.items[0].key;
assert.equal(source.resolveMany([key,key]).length,1,'batch resolves unique keys in one validation');assert.equal(source.resolveMany([key,'unknown']),null,'unknown action aborts entire review');

assert.equal(first.items[0].detail,'native description');assert.ok(!('raw' in first.items[0]));assert.ok(!('descriptor' in first.items[0]));assert.equal(source.resolve(key).raw,item);assert.equal(first.unknownSlots[0],'mystery');
first.items[0].traits.push('UI only');assert.equal(item.type.length,1);assert.equal(JSON.stringify(root.V),before);
root.setup.clothes.upper[0]={...definition};assert.equal(source.resolve(key),null,'same-value definition replacement invalidates binding');source.read('upper');const descriptorKey=source.read('upper').items[0].key;assert.equal(source.resolveMany([descriptorKey]).length,1);
item.integrity=60;assert.equal(source.resolve(key),null,'in-place native update invalidates old operation');const second=source.read('upper');assert.notEqual(second.items[0].key,key);assert.equal(second.items[0].durability,60);
root.setup.colourName=()=> 'translated';assert.equal(source.resolve(second.items[0].key),null,'derived display changes invalidate projection');assert.equal(source.read('upper').items[0].colour,'translated');
const contextualKey=source.read('upper').items[0].key;root.setup.colourName=()=>{current=false;return 'translated'};assert.equal(source.resolve(contextualKey),null,'page changes during native display helper invalidate dispatch');current=true;root.setup.colourName=()=> 'translated';
const fresh=source.read('upper').items[0].key;root.V.wardrobe.upper[0]={...item};assert.equal(source.resolve(fresh),null,'same-value replacement is not same native identity');
const replacement=source.read('upper').items[0].key;current=false;assert.equal(source.resolve(replacement),null,'page ownership lost');assert.equal(source.read('upper'),null);current=true;
root.V.wardrobe.over_upper=[item];root.V.worn.over_upper={name:'naked'};root.setup.clothes.over_upper=[definition];
const extension=moduleObject.exports.createWardrobeSource(root,()=>({over_upper:'外套上装'}),()=>current);
root.V.wardrobe.charm=[];root.V.worn.charm={name:'naked'};root.setup.clothes.charm=[definition];
assert.ok(source.read('upper').unknownSlots.includes('charm'),'empty new slot remains discoverable');
root.V.wardrobe.over_head=[];root.V.worn.over_head={name:'naked'};root.setup.clothes.over_head=[definition];
assert.ok(!source.read('upper').unknownSlots.includes('over_head'),'empty optional vanilla slots do not flood unknown-content notices');
assert.equal(extension.read('over_upper').items[0].detail,'native description');assert.equal(extension.read('over_upper').categoryNote,'','no experimental category copy');extension.destroy();
// Search bindings span only known categories and retain original slot/object identity.
root.V.wardrobe.lower=[{...item}];root.V.worn.lower={name:'naked'};root.setup.clothes.lower=[{...definition}];
const cross=moduleObject.exports.createWardrobeSource(root,()=>({upper:'上装',lower:'下装'}),()=>current);
const all=cross.read('upper',true);assert.equal(all.items.length,2);assert.equal(all.items[0].name,all.items[1].name);
assert.deepEqual(Array.from(all.items,i=>i.slotLabel),['上装','下装']);assert.notEqual(all.items[0].key,all.items[1].key);
assert.equal(cross.resolve(all.items[1].key).slot,'lower');assert.equal(cross.resolve(all.items[1].key).raw,root.V.wardrobe.lower[0]);
assert.ok(all.unknownSlots.includes('mystery'));assert.ok(!all.items.some(i=>i.key.startsWith('mystery:')));
root.V.wardrobe.lower[0]={...root.V.wardrobe.lower[0]};assert.equal(cross.resolve(all.items[1].key),null,'same-valued cross-category replacement refuses stale wear');
let searched=cross.read('upper',true);root.V.wardrobe.lower.unshift({...item});assert.equal(cross.resolve(searched.items[1].key),null,'index changes refuse stale wear');
searched=cross.read('upper',true);root.setup.clothes.lower[0]={...definition};assert.equal(cross.resolve(searched.items[1].key),null,'definition replacement refuses stale wear');
const normal=cross.read('upper');assert.ok(normal.items.every(i=>i.slotLabel===undefined));assert.equal(cross.resolve(searched.items[0].key),null,'changing search scope expires old keys');
const labelsOnly=moduleObject.exports.createWardrobeSource(root,()=>({upper:'上装'}),()=>current);labelsOnly.read('upper');assert.equal(labelsOnly.read('upper',true).items[0].slotLabel,'上装','single-category search still labels results');labelsOnly.destroy();
const final=cross.read('upper',true);root.V.location='school';assert.equal(cross.resolve(final.items[0].key),null,'scene change refuses search result');root.V.location='home';cross.destroy();
source.destroy();assert.equal(source.resolve(replacement),null);assert.equal(source.read('upper'),null);assert.equal(source.resolveMany([replacement]),null);
assert.equal(source.resolveMany([replacement]),null);
console.log('PASS M2 projection: no native refs/writes; content/identity/page invalidation; unknown slots; disposal');
