const assert=require('node:assert/strict'),vm=require('node:vm'),path=require('node:path'),{buildSync}=require('esbuild');
const code=buildSync({entryPoints:[path.join(__dirname,'../src/wardrobe/slot-mappings.ts')],bundle:true,platform:'node',format:'cjs',write:false}).outputFiles[0].text;
const moduleObject={exports:{}};vm.runInNewContext(code,{module:moduleObject,exports:moduleObject.exports});
let version='4.1.1';const registry=moduleObject.exports.createSlotMappings(()=>version);
const item={name:'coat'},inventory={over_upper:[item]},worn={over_upper:{name:'naked'}},definitions={over_upper:[item]};
const snapshot={inventory,worn,setup:{clothes:definitions},variables:{debug:false}};
const before=JSON.stringify(snapshot),spec={id:'ReOverfits',target:{name:'ReOverfits',versions:['4.1.1']},slots:{over_upper:'外套上装'}};
const handle=registry.register(spec);spec.slots.over_upper='mutated';spec.target.versions[0]='4.2.0';
assert.equal(registry.labels(snapshot).over_upper,'外套上装');assert.equal(JSON.stringify(snapshot),before);assert.equal(inventory.over_upper[0],item);
version='4.2.0';assert.equal(registry.labels(snapshot).over_upper,undefined);version='4.1.1';
assert.equal(registry.labels({...snapshot,inventory:{}}).over_upper,undefined);
assert.equal(registry.labels({...snapshot,worn:{}}).over_upper,undefined);
assert.equal(registry.labels({...snapshot,setup:{clothes:{over_upper:[]}}}).over_upper,undefined);
assert.throws(()=>registry.register({...spec,id:'Other'}),/already mapped/);
assert.throws(()=>registry.register({...spec,id:'ReOverfits'}),/duplicate/);
assert.throws(()=>registry.register({...spec,id:'Core',slots:{upper:'override'}}),/Invalid wardrobe slot/);
assert.throws(()=>registry.register({...spec,id:'Reserved',slots:JSON.parse('{"__proto__":"bad"}')}),/Invalid wardrobe slot/);
handle.destroy();handle.destroy();assert.equal(registry.labels(snapshot).over_upper,undefined);
registry.register({...spec,target:{name:'ReOverfits',versions:['4.1.1']}});registry.destroy();assert.equal(registry.labels(snapshot).over_upper,undefined);
assert.throws(()=>registry.register(spec),/disposed/);
console.log('PASS semantic mapping: target/data gates, no state mutation, input copy, collision guards, revoke/dispose');
