const assert=require('node:assert/strict'),path=require('node:path'),vm=require('node:vm'),{buildSync}=require('esbuild');
const m={exports:{}};vm.runInNewContext(buildSync({entryPoints:[path.join(__dirname,'../src/wardrobe/operations.ts')],bundle:true,write:false,format:'cjs',platform:'node'}).outputFiles[0].text,{module:m,exports:m.exports});
const {relatedPieces,pieces,repairMinutes,canRepair,destinations,transferProblem}=m.exports;
const primary={name:'outfit',colour:'custom',accessory_colour:'custom',colourCustom:'blue',accessory_colourCustom:'white',outfitPrimary:{lower:'skirt'}};
const secondary={name:'skirt',colour:'custom',accessory:0,colourCustom:'blue',accessory_colour:'custom',outfitSecondary:['upper','outfit']};
const inventory={upper:[primary],lower:[secondary],space:4},target={name:'Target',unlocked:true,shopSend:true,transfer:true,upper:[],lower:[],space:1};
const s={location:'wardrobe',inventory,variables:{sewingKit:1,location:'home',settings:{multipleWardrobes:true},wardrobe:inventory,wardrobes:{wardrobe:{unlocked:true,shopSend:true,transfer:true},target}}};const e={slot:'upper',index:0,raw:primary};
assert.equal(relatedPieces(inventory,'upper',primary).length,1,'accessory-free secondary matches without custom accessory metadata');assert.equal(pieces(s,e).length,2);assert.equal(repairMinutes(inventory,[e]),10);assert.equal(canRepair(s),true);assert.equal(destinations(s)[0].key,'target');assert.equal(transferProblem(s,[e],'target'),'');
target.lower.push({});assert.match(transferProblem(s,[e],'target'),/容量/,'linked lower part consumes target space');target.lower=[];
const spare={...e,raw:{name:'spare'}};assert.match(transferProblem(s,[e,spare],'target'),/容量/,'batch aggregate capacity checked before any writes');
s.variables.settings.multipleWardrobes=false;assert.equal(destinations(s).length,0);assert.match(transferProblem(s,[e],'target'),/不可/);s.variables.settings.multipleWardrobes=true;s.variables.wardrobes.wardrobe.transfer=false;assert.equal(destinations(s).length,0);s.variables.wardrobes.wardrobe.transfer=true;
s.variables.location='school';assert.equal(canRepair(s),false);s.variables.location='home';s.variables.sewingKit=0;assert.equal(canRepair(s),false);
delete primary.colourCustom;delete secondary.colourCustom;assert.equal(relatedPieces(inventory,'upper',primary).length,0,'missing custom colour identity never pairs');primary.colour='blue';secondary.colour='blue';secondary.accessory=1;delete primary.accessory_colourCustom;delete secondary.accessory_colourCustom;assert.equal(relatedPieces(inventory,'upper',primary).length,0,'missing custom accessory identity never pairs');
console.log('PASS operation capabilities, exact outfit matching, linked capacity, batch capacity, repair time.');
const nativeModule={exports:{}};let macro='';
vm.runInNewContext(buildSync({entryPoints:[path.join(__dirname,'../src/wardrobe/native.ts')],bundle:true,write:false,format:'cjs',platform:'node'}).outputFiles[0].text,{module:nativeModule,exports:nativeModule.exports,document:{createElement:()=>({})}});
const native=nativeModule.exports.createNativeWardrobe({Wikifier:class{constructor(_node,source){macro=source}}},{measure:(_phase,fn)=>fn()});
native.action('transfer','upper',0,'储物柜');assert.ok(macro.startsWith('<<set _wardrobeTransfer="储物柜">>'));assert.ok(!macro.includes('$_wardrobeTransfer'));
assert.throws(()=>native.action('delete','upper','strip'),/参数/);assert.throws(()=>native.action('wear','feet','towel'),/毛巾/);assert.throws(()=>native.action('wear','lower','large_towel'),/毛巾/);
native.action('transfer','upper',0,'custom>>name');assert.ok(macro.includes('custom\\u003e\\u003ename'),'mod wardrobe names cannot close the generated macro');
console.log('PASS native transfer temporary variable, mod wardrobe name encoding, towel and destructive-mode validation.');
